---
properties:
  cc:
    default_stack: sle12
    diego:
      docker_staging_stack: sle12
      lifecycle_bundles:
        'buildpack/sle12':      "buildpack_app_lifecycle/buildpack_app_lifecycle.tgz"
        'buildpack/cflinuxfs2': "buildpack_app_lifecycle/buildpack_app_lifecycle.tgz"
        docker:                 "docker_app_lifecycle/docker_app_lifecycle.tgz"
    stacks:
    - name: "cflinuxfs2"
      description: "Cloud Foundry Linux-based filesystem"
    - name: "sle12"
      description: "SLE-based filesystem"
  diego:
    rep:
      preloaded_rootfses:
      - "sle12:/var/vcap/packages/cf-sle12/rootfs.tar"
      - "cflinuxfs2:/var/vcap/packages/cflinuxfs2/rootfs.tar"
  garden:
    persistent_image_list:
    - "/var/vcap/packages/cf-sle12/rootfs.tar"
    - "/var/vcap/packages/cflinuxfs2/rootfs.tar"
