---
suse-stack-name: &suse-stack-name opensuse42

suse-bundles: &suse-bundles
  'buildpack/opensuse42': "buildpack_app_lifecycle/buildpack_app_lifecycle.tgz"
  'buildpack/cflinuxfs2': "buildpack_app_lifecycle/buildpack_app_lifecycle.tgz"
  docker:                 "docker_app_lifecycle/docker_app_lifecycle.tgz"

suse-stacks: &suse-stacks
  - name: cflinuxfs2
    description: "Cloud Foundry Linux-based filesystem"
  - name: opensuse42
    description: "openSUSE-based filesystem"

suse-roots: &suse-roots
  - "opensuse42:/var/vcap/packages/opensuse42/rootfs.tar"
  - "cflinuxfs2:/var/vcap/packages/cflinuxfs2/rootfs.tar"

suse-images: &suse-images
  - "/var/vcap/packages/opensuse42/rootfs.tar"
  - "/var/vcap/packages/cflinuxfs2/rootfs.tar"

# Append common parts here
