---
PrePush:
  SyncNotes:
    enabled: true
    command: ./vendor/github.com/hpe-cloud-garage/git-notary/hooks/pre-push/sync-notes
  BranchHasNotes:
    enabled: true
    command: ./vendor/github.com/hpe-cloud-garage/git-notary/hooks/pre-push/branch-has-notes
PreCommit:
  JsonSyntax:
    enabled: true
  YamlSyntax:
    enabled: true
