---
properties:
  cc:
    droplets:
      droplet_directory_key: the_key
    buildpacks:
      buildpack_directory_key: bd_key
    staging_upload_user: username
    staging_upload_password: password
    bulk_api_password: password
    db_encryption_key: the_key
  ccdb:
    roles:
    - name: ccadmin
      password: admin_password
      tag: admin
  domain: example.com
  loggregator_endpoint:
    shared_secret: loggregator_endpoint_secret
  nats:
    user: nats_user
    password: nats_password
  router:
    enable_ssl: true
    ssl_cert: ''
    ssl_key: ''
    status:
      user: router_user
      password: router_password
  uaa:
    admin:
      client_secret: admin_secret
    batch:
      username: batch_username
      password: batch_password
    cc:
      client_secret: cc_client_secret
    clients:
      app-direct:
        secret: app-direct_secret
      developer_console:
        secret: developer_console_secret
      notifications:
        secret: notification_secret
      login:
        secret: login_client_secret
      doppler:
        secret: doppler_secret
      cloud_controller_username_lookup:
        secret: cloud_controller_username_lookup_secret
      gorouter:
        secret: gorouter_secret
    jwt:
      verification_key: vk
      signing_key: sk
    scim:
      users: []
  uaadb:
    roles:
    - name: uaaadmin
      password: admin_password
      tag: admin
