---
properties:
  cc:
    droplets:
      droplet_directory_key: the_key
    buildpacks:
      buildpack_directory_key: bd_key
    staging_upload_user: username
    staging_upload_password: password
    bulk_api_password: password
    db_encryption_key: the_key
  ccdb:
    roles:
    - name: ccadmin
      password: admin_password
      tag: admin
  cf-usb:
    broker:
      username: cf-usb_username
      password: cf-usb_password
    management:
      uaa:
        secret: cf-usb_secret
  domain: example.com
  loggregator_endpoint:
    shared_secret: loggregator_endpoint_secret
  nats:
    user: nats_user
    password: nats_password
  router:
    ssl_cert: ''
    ssl_key: ''
    status:
      user: router_user
      password: router_password
  uaadb:
    roles:
    - name: uaaadmin
      password: admin_password
      tag: admin
