---
properties:
  cc:
    staging_upload_password: password
    bulk_api_password: password
    db_encryption_key: the_key
  ccdb:
    roles:
    - name: ccadmin
      password: admin_password
      tag: admin
  cf-usb:
    broker:
      password: cf-usb_password
    management:
      uaa:
        secret: cf-usb_secret
  couchdb:
    password: couchdb_password
  domain: example.com
  nats:
    password: nats_password
  router:
    ssl_cert: ''
    ssl_key: ''
    status:
      password: router_password
    route_services_secret: null
  smoke_tests:
    api: api.((DOMAIN))
    apps_domain: [ ((DOMAIN)) ]
    password: ((CLUSTER_ADMIN_PASSWORD))
  uaa:
    admin:
      client_secret: admin_secret
    clients:
      cf-autoscaler-client:
        secret: cf-autoscaler-client-secret
      cf-usb:
        secret: cf-usb_secret
      cc_routing:
        secret: cc_routing_secret
      cc-service-dashboards:
        secret: cc-broker-secret
      hcf-sso:
        secret: hcf_sso_secret
      notifications:
        secret: notification_secret
      tcp_emitter:
         secret: tcp-emitter-secret
      tcp_router:
        secret: tcp-router-secret
      login:
        secret: login_client_secret
      doppler:
        secret: doppler_secret
      cloud_controller_username_lookup:
        secret: cloud_controller_username_lookup_secret
      gorouter:
        secret: gorouter_secret
      ssh-proxy:
        secret: ssh-proxy_secret
    jwt:
      verification_key: vk
      signing_key: sk
    scim:
      users: []
  uaadb:
    roles:
    - name: uaaadmin
      password: admin_password
      tag: admin
