---
properties:
  acceptance_tests: null
  app_domains:
  - example.com
  app_ssh: null
  cc:
    allow_app_ssh_access: true
    allowed_cors_domains: []
    app_events:
      cutoff_age_in_days: 31
    app_usage_events:
      cutoff_age_in_days: 31
    audit_events:
      cutoff_age_in_days: 31
    broker_client_default_async_poll_interval_seconds: 60
    broker_client_max_async_poll_duration_minutes: 10080
    broker_client_timeout_seconds: 70
    buildpacks:
      buildpack_directory_key: bd_key
      cdn: null
      fog_connection: null
    bulk_api_password: password
    client_max_body_size: 15M
    db_encryption_key: the_key
    db_logging_level: debug2
    default_app_disk_in_mb: 1024
    default_app_memory: 1024
    default_buildpacks:
    - name: staticfile_buildpack
      package: buildpack_staticfile
    - name: java_buildpack
      package: buildpack_java
    - name: ruby_buildpack
      package: buildpack_ruby
    - name: nodejs_buildpack
      package: buildpack_nodejs
    - name: go_buildpack
      package: buildpack_go
    - name: python_buildpack
      package: buildpack_python
    - name: php_buildpack
      package: buildpack_php
    - name: binary_buildpack
      package: buildpack_binary
    default_health_check_timeout: 60
    default_quota_definition: default
    default_running_security_groups:
    - public_networks
    - dns
    default_staging_security_groups:
    - public_networks
    - dns
    default_to_diego_backend: false
    development_mode: false
    directories: null
    disable_custom_buildpacks: false
    droplets:
      cdn: null
      droplet_directory_key: the_key
      fog_connection: null
    external_host: api
    external_protocol: http
    install_buildpacks:
    - name: staticfile_buildpack
      package: buildpack_staticfile
    - name: java_buildpack
      package: buildpack_java
    - name: ruby_buildpack
      package: buildpack_ruby
    - name: nodejs_buildpack
      package: buildpack_nodejs
    - name: go_buildpack
      package: buildpack_go
    - name: python_buildpack
      package: buildpack_python
    - name: php_buildpack
      package: buildpack_php
    - name: binary_buildpack
      package: buildpack_binary
    internal_api_password: password
    internal_api_user: internal_user
    jobs:
      app_bits_packer:
        timeout_in_seconds: null
      app_events_cleanup:
        timeout_in_seconds: null
      app_usage_events_cleanup:
        timeout_in_seconds: null
      blobstore_delete:
        timeout_in_seconds: null
      blobstore_upload:
        timeout_in_seconds: null
      droplet_deletion:
        timeout_in_seconds: null
      droplet_upload:
        timeout_in_seconds: null
      generic:
        number_of_workers: null
      global:
        timeout_in_seconds: 14400
      model_deletion:
        timeout_in_seconds: null
    logging_level: debug2
    maximum_app_disk_in_mb: 2048
    maximum_health_check_timeout: 180
    min_cli_version: null
    min_recommended_cli_version: null
    newrelic:
      capture_params: false
      developer_mode: false
      environment_name: null
      license_key: null
      monitor_mode: false
      transaction_tracer:
        enabled: true
        record_sql: obfuscated
    packages:
      app_package_directory_key: example.com-cc-packages
      cdn: null
      fog_connection: null
      max_package_size: 1073741824
    quota_definitions:
      default:
        memory_limit: 10240
        non_basic_services_allowed: true
        total_routes: 1000
        total_services: 100
    resource_pool:
      cdn: null
      fog_connection: null
      resource_directory_key: example.com-cc-resources
    security_group_definitions:
    - name: public_networks
      rules:
      - destination: 0.0.0.0-9.255.255.255
        protocol: all
      - destination: 11.0.0.0-169.253.255.255
        protocol: all
      - destination: 169.255.0.0-172.15.255.255
        protocol: all
      - destination: 172.32.0.0-192.167.255.255
        protocol: all
      - destination: 192.169.0.0-255.255.255.255
        protocol: all
    - name: dns
      rules:
      - destination: 0.0.0.0/0
        ports: "53"
        protocol: tcp
      - destination: 0.0.0.0/0
        ports: "53"
        protocol: udp
    srv_api_uri: https://api.example.com
    stacks: null
    staging_upload_password: password
    staging_upload_user: username
    system_buildpacks:
    - name: staticfile_buildpack
      package: buildpack_staticfile
    - name: java_buildpack
      package: buildpack_java
    - name: ruby_buildpack
      package: buildpack_ruby
    - name: nodejs_buildpack
      package: buildpack_nodejs
    - name: go_buildpack
      package: buildpack_go
    - name: python_buildpack
      package: buildpack_python
    - name: php_buildpack
      package: buildpack_php
    - name: binary_buildpack
      package: buildpack_binary
    thresholds:
      api:
        alert_if_above_mb: null
        restart_if_above_mb: null
        restart_if_consistently_above_mb: null
      worker:
        alert_if_above_mb: null
        restart_if_above_mb: null
        restart_if_consistently_above_mb: null
    user_buildpacks: []
    users_can_select_backend: true
  ccdb:
    address: 0.0.0.4
    databases:
    - name: ccdb
      tag: cc
    db_scheme: postgres
    port: 5524
    roles:
    - name: ccadmin
      password: admin_password
      tag: admin
  collector: null
  consul:
    agent:
      log_level: null
      servers:
        lan:
        - 0.0.0.12
    agent_cert: null
    agent_key: null
    ca_cert: null
    encrypt_keys: []
    require_ssl: null
    server_cert: null
    server_key: null
  dea_next:
    # Used in ccng/templates/cc_api.yml.erb
    advertise_interval_in_seconds: 5
    # Used in cc_ng and cc_worker
    staging_disk_limit_mb: 6144
    # Used in cc_ng and cc_worker
    staging_memory_limit_mb: 1024
  description: Helion Cloud Foundry
  domain: example.com
  doppler:
    blacklisted_syslog_ranges: null
    debug: false
    maxRetainedLogMessages: 100
    port: 4443
    unmarshaller_count: 5
  doppler_endpoint:
    shared_secret: loggregator_endpoint_secret
  dropsonde:
    enabled: true
  etcd:
    ca_cert: null
    client_cert: null
    client_key: null
    cluster: null
    machines:
    - 0.0.0.8
    peer_require_ssl: null
    require_ssl: null
    server_cert: null
    server_key: null
  etcd_metrics_server:
    nats:
      machines:
      - 0.0.0.2
      password: nats_password
      username: nats_user
  hm9000:
    # Used in cc_ng and cc_worker
    url: https://hm9000.example.com
  logger_endpoint:
    port: 4443
  loggregator:
    blacklisted_syslog_ranges: null
    debug: false
    maxRetainedLogMessages: 100
  loggregator_endpoint:
    shared_secret: loggregator_endpoint_secret
  login:
    analytics:
      code: null
      domain: null
    asset_base_url: null
    brand: oss
    catalina_opts: null
    enabled: true
    invitations_enabled: null
    links:
      home: https://console.example.com
      network: null
      passwd: https://console.example.com/password_resets/new
      signup: https://console.example.com/register
      signup-network: null
    logout:
      redirect:
        url: /login?template=openstack
    messages: null
    notifications:
      url: null
    protocol: https
    restricted_ips_regex: 10\.\d{1,3}\.\d{1,3}\.\d{1,3}|192\.168\.\d{1,3}\.\d{1,3}|169\.254\.\d{1,3}\.\d{1,3}|127\.\d{1,3}\.\d{1,3}\.\d{1,3}|172\.1[6-9]{1}\.\d{1,3}\.\d{1,3}|172\.2[0-9]{1}\.\d{1,3}\.\d{1,3}|172\.3[0-1]{1}\.\d{1,3}\.\d{1,3}
    saml: null
    self_service_links_enabled: null
    signups_enabled: null
    smtp: null
    spring_profiles: null
    tiles: null
    uaa_base: null
    uaa_certificate: null
    url: null
  metron_agent:
    deployment: null
  metron_endpoint:
    shared_secret: loggregator_endpoint_secret
  nats:
    address: 0.0.0.2
    debug: false
    machines:
    - 0.0.0.2
    monitor_port: 0
    password: nats_password
    port: 4222
    prof_port: 0
    trace: false
    user: nats_user
  nfs_server:
    address: 0.0.0.3
    allow_from_entries:
    - null
    - null
    share: null
  request_timeout_in_seconds: 900
  router:
    cipher_suites: TLS_RSA_WITH_RC4_128_SHA:TLS_RSA_WITH_AES_128_CBC_SHA
    enable_ssl: true
    extra_headers_to_log: null
    logrotate:
      freq_min: 20
      rotate: 5
      size: 3M
    requested_route_registration_interval_in_seconds: null
    route_service_secret: null
    route_service_timeout: null
    secure_cookies: null
    ssl_skip_validation: null
    status:
      password: router_password
      user: router_user
  smoke_tests: null
  ssl:
    skip_cert_verify: false
  support_address: http://support.cloudfoundry.com
  syslog_daemon_config: null
  system_domain: example.com
  system_domain_organization: null
  uaa:
    admin:
      client_secret: admin_secret
    authentication:
      policy:
        countFailuresWithinSeconds: null
        lockoutAfterFailures: null
        lockoutPeriodSeconds: null
    batch:
      password: batch_password
      username: batch_username
    catalina_opts: -Xmx768m -XX:MaxPermSize=256m
    cc:
      client_secret: cc_client_secret
    clients:
      app-direct:
        secret: app-direct_secret
      cloud_controller_username_lookup:
        authorities: scim.userids
        authorized-grant-types: client_credentials
        secret: cloud_controller_username_lookup_secret
      developer_console:
        secret: developer_console_secret
      doppler:
        authorities: uaa.resource
        override: true
        secret: doppler_secret
      gorouter:
        authorities: clients.read,clients.write,clients.admin,route.admin,route.advertise
        authorized-grant-types: client_credentials,refresh_token
        scope: openid,cloud_controller_service_permissions.read
        secret: gorouter_secret
      login:
        authorities: oauth.login,scim.write,clients.read,notifications.write,critical_notifications.write,emails.write,scim.userids,password.write
        authorized-grant-types: authorization_code,client_credentials,refresh_token
        override: true
        redirect-uri: https://login.example.com
        scope: openid,oauth.approvals
        secret: login_client_secret
      notifications:
        authorities: cloud_controller.admin,scim.read
        authorized-grant-types: client_credentials
        secret: notification_secret
    database:
      abandoned_timeout: 600
      log_abandoned: true
      max_connections: 100
      max_idle_connections: 10
      remove_abandoned: true
    issuer: https://uaa.example.com
    jwt:
      signing_key: sk
      verification_key: vk
    ldap: null
    login: null
    newrelic: null
    no_ssl: false
    require_https: null
    restricted_ips_regex: 10\.\d{1,3}\.\d{1,3}\.\d{1,3}|192\.168\.\d{1,3}\.\d{1,3}|169\.254\.\d{1,3}\.\d{1,3}|127\.\d{1,3}\.\d{1,3}\.\d{1,3}|172\.1[6-9]{1}\.\d{1,3}\.\d{1,3}|172\.2[0-9]{1}\.\d{1,3}\.\d{1,3}|172\.3[0-1]{1}\.\d{1,3}\.\d{1,3}
    scim:
      external_groups: null
      userids_enabled: true
      users: []
      user:
        override: true
    spring_profiles: null
    url: https://uaa.example.com
    user: null
    zones: null
  uaadb:
    address: 0.0.0.4
    databases:
    - name: uaadb
      tag: uaa
    db_scheme: postgresql
    port: 5524
    roles:
    - name: uaaadmin
      password: admin_password
      tag: admin
