---
roles:
- name: acceptance_tests
  is_task: true
  scripts:
  - fix_local_ip_for_overlay_networking.sh
  jobs:
  - name: acceptance-tests
    release_name: cf
- name: api
  scripts:
  - fix_local_ip_for_overlay_networking.sh
  jobs:
  - name: cloud_controller_ng
    release_name: cf
  - name: routing-api
    release_name: cf
  - name: statsd-injector
    release_name: cf
  - name: consul_agent
    release_name: cf
  - name: metron_agent
    release_name: cf
  - name: route_registrar
    release_name: cf
  - name: cf-set-proxy
    release_name: hcf-deployment-hooks
  processes:
  - name: cloud_controller_ng
  - name: cloud_controller_worker_local_1
  - name: cloud_controller_migration
  - name: routing-api
  - name: route_registrar
  - name: metron_agent
  - name: consul_agent
- name: api_worker
  scripts:
  - fix_local_ip_for_overlay_networking.sh
  jobs:
  - name: cloud_controller_worker
    release_name: cf
  - name: consul_agent
    release_name: cf
  - name: metron_agent
    release_name: cf
  processes:
  - name: cloud_controller_worker_1
  - name: metron_agent
  - name: consul_agent
- name: clock_global
  scripts:
  - fix_local_ip_for_overlay_networking.sh
  jobs:
  - name: cloud_controller_clock
    release_name: cf
  - name: consul_agent
    release_name: cf
  - name: metron_agent
    release_name: cf
  processes:
  - name: cloud_controller_clock
  - name: metron_agent
  - name: consul_agent
- name: consul
  scripts:
  - fix_local_ip_for_overlay_networking.sh
  - consul_startup.sh
  jobs:
  - name: consul_agent
    release_name: cf
  - name: metron_agent
    release_name: cf
  processes:
  - name: metron_agent
  - name: consul_agent
- name: doppler
  scripts:
  - fix_local_ip_for_overlay_networking.sh
  - write_dns_health_check_doppler.sh
  jobs:
  - name: doppler
    release_name: cf
  - name: syslog_drain_binder
    release_name: cf
  - name: consul_agent
    release_name: cf
  - name: metron_agent
    release_name: cf
  - name: route_registrar
    release_name: cf
  processes:
  - name: doppler
  - name: route_registrar
  - name: consul_agent
  - name: syslog_drain_binder
- name: etcd
  scripts:
  - fix_local_ip_for_overlay_networking.sh
  - write_dns_health_check_etcdlog.sh
  jobs:
  - name: etcd
    release_name: cf
  - name: etcd_metrics_server
    release_name: cf
  - name: consul_agent
    release_name: cf
  - name: metron_agent
    release_name: cf
  processes:
  - name: etcd_metrics_server
  - name: etcd metron_agent
  - name: consul_agent
- name: ha_proxy
  jobs:
  - name: haproxy
    release_name: cf
  - name: consul_agent
    release_name: cf
  - name: metron_agent
    release_name: cf
  processes:
  - name: consul_template
  - name: haproxy
  - name: metron_agent
  - name: consul_agent
- name: loggregator_trafficcontroller
  scripts:
  - fix_local_ip_for_overlay_networking.sh
  - write_dns_health_check_trafficcontroller.sh
  jobs:
  - name: loggregator_trafficcontroller
    release_name: cf
  - name: consul_agent
    release_name: cf
  - name: metron_agent
    release_name: cf
  - name: route_registrar
    release_name: cf
  processes:
  - name: loggregator_trafficcontroller
  - name: route_registrar
  - name: consul_agent
- name: nats
  scripts:
  - fix_local_ip_for_overlay_networking.sh
  - write_dns_health_check_nats.sh
  jobs:
  - name: nats
    release_name: cf
  - name: nats_stream_forwarder
    release_name: cf
  - name: consul_agent
    release_name: cf
  - name: metron_agent
    release_name: cf
  processes:
  - name: metron_agent
  - name: consul_agent
  - name: nats
  - name: nats_stream_forwarder
- name: router
  scripts:
  - fix_local_ip_for_overlay_networking.sh
  jobs:
  - name: gorouter
    release_name: cf
  - name: consul_agent
    release_name: cf
  - name: metron_agent
    release_name: cf
  processes:
  - name: gorouter
  - name: metron_agent
  - name: consul_agent
- name: smoke_tests
  is_task: true
  scripts:
  - fix_local_ip_for_overlay_networking.sh
  jobs:
  - name: smoke-tests
    release_name: cf
- name: stats
  scripts:
  - fix_local_ip_for_overlay_networking.sh
  - write_dns_health_check_stats.sh
  jobs:
  - name: collector
    release_name: cf
  - name: consul_agent
    release_name: cf
  - name: metron_agent
    release_name: cf
  processes:
  - name: collector
  - name: metron_agent
  - name: consul_agent
- name: uaa
  scripts:
  - fix_local_ip_for_overlay_networking.sh
  jobs:
  - name: uaa
    release_name: cf
  - name: consul_agent
    release_name: cf
  - name: metron_agent
    release_name: cf
  - name: route_registrar
    release_name: cf
  processes:
  - name: uaa
  - name: consul_agent
- name: cf-usb
  jobs:
  - name: cf-usb
    release_name: cf-usb
  - name: consul_agent
    release_name: cf
  - name: route_registrar
    release_name: cf
  processes:
  - name: usb
  - name: route_registrar
  - name: consul_agent
- name: diego_database
  scripts:
  - fix_local_ip_for_overlay_networking.sh
  jobs:
  - name: etcd
    release_name: etcd
  - name: bbs
    release_name: diego
  - name: consul_agent
    release_name: cf
  - name: metron_agent
    release_name: cf
  processes:
  - name: bbs
  - name: etcd
  - name: metron_agent
  - name: consul_agent
- name: diego_brain
  scripts:
  - fix_local_ip_for_overlay_networking.sh
  jobs:
  - name: consul_agent
    release_name: cf
  - name: auctioneer
    release_name: diego
  - name: converger
    release_name: diego
  - name: metron_agent
    release_name: cf
  processes:
  - name: converger
  - name: auctioneer
  - name: metron_agent
  - name: consul_agent
- name: diego_cell
  scripts:
  - prevent_apparmor_disable.sh
  - fix_local_ip_for_overlay_networking.sh
  - fix_linux_garden_dns.sh
  jobs:
  - name: rep
    release_name: diego
  - name: consul_agent
    release_name: cf
  - name: garden
    release_name: garden-linux
  - name: rootfses
    release_name: diego
  - name: metron_agent
    release_name: cf
  processes:
  - name: rootfses
  - name: metron_agent
  - name: consul_agent
  - name: rep
  - name: garden
- name: diego_cc_bridge
  scripts:
  - fix_local_ip_for_overlay_networking.sh
  jobs:
  - name: stager
    release_name: diego
  - name: nsync
    release_name: diego
  - name: tps
    release_name: diego
  - name: cc_uploader
    release_name: diego
  - name: consul_agent
    release_name: cf
  - name: metron_agent
    release_name: cf
  processes:
  - name: stager
  - name: tps_watcher
  - name: nsync_listener
  - name: nsync_bulker
  - name: metron_agent
  - name: consul_agent
- name: diego_route_emitter
  scripts:
  - fix_local_ip_for_overlay_networking.sh
  jobs:
  - name: route_emitter
    release_name: diego
  - name: consul_agent
    release_name: cf
  - name: metron_agent
    release_name: cf
  processes:
  - name: route_emitter
  - name: metron_agent
  - name: consul_agent
- name: diego_access
  scripts:
  - fix_local_ip_for_overlay_networking.sh
  jobs:
  - name: ssh_proxy
    release_name: diego
  - name: consul_agent
    release_name: cf
  - name: metron_agent
    release_name: cf
  - name: file_server
    release_name: diego
  processes:
  - name: file_server
  - name: metron_agent
  - name: ssh_proxy
  - name: consul_agent
- name: mysql
  scripts:
  - write_dns_health_check_mysql.sh
  jobs:
  - name: mysql
    release_name: cf-mysql
  - name: consul_agent
    release_name: cf
  processes:
  - name: consul_agent
  - name: mariadb_ctrl
  - name: galera-healthcheck
  - name: gra-log-purger-executable
- name: mysql_proxy
  scripts:
  - write_dns_health_check_mysql_proxy.sh
  jobs:
  - name: proxy
    release_name: cf-mysql
  - name: consul_agent
    release_name: cf
  processes:
  - name: consul_agent
  - name: switchboard
